version: 2.1

orbs:
  haskell: haskell-works/haskell-build@2.0.0
  github: haskell-works/github-release@1.3.0
  hackage: haskell-works/hackage@1.1.0

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build-with-binary-cache:
          name: GHC 8.6.5
          executor: haskell/ghc-8_6_5
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          workspace-dir: workspace/ghc-8.6.5
          write-result-workspace: true

      - github/release-cabal:
          context: haskell-ci
          name: GitHub Release
          attach-workspace: true
          source-env-file: ./workspace/ghc-8.6.5/project.env
          requires:
            - GHC 8.6.5
          checkout: true
          before-release:
            - run:
                name: Prepare environment for release
                command: |
                  tar zcvf /tmp/artefacts/${CIRCLE_PROJECT_REPONAME}_${BUILD_ARCH}_${BUILD_OS_NAME}.tar.gz -C ./workspace/ghc-8.6.5/dist/ ./${BUILD_EXE_NAME}
          filters:
            branches:
              only: master

      - hackage/upload:
          context: haskell-ci
          publish: true
          requires:
            - GitHub Release
